name: name
on:
  push:
    branches:
      - "auction"
    paths:
      - "/client-web"
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3